# Generated by Django 5.2.4 on 2025-11-12 11:44

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('intro_badge', models.CharField(blank=True, max_length=100, null=True)),
                ('intro_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('intro_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('founder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('founder_role', models.CharField(blank=True, max_length=100, null=True)),
                ('founder_quote', models.TextField(blank=True, null=True)),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='about/founder/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/main/')),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='about/overlay/')),
                ('years_of_excellence', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Bootstrap icon class, e.g., bi bi-key', max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, help_text="e.g., '+', '%', etc.", max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='ads/')),
                ('short_description', models.TextField()),
                ('detail_content', ckeditor.fields.RichTextField()),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('badge_icon', models.CharField(default='bi bi-star', max_length=50)),
                ('special_offer_title', models.CharField(blank=True, max_length=200)),
                ('special_offer_description', ckeditor.fields.RichTextField(blank=True)),
                ('text_size_heading', models.CharField(default='1.6em', max_length=10)),
                ('text_size_paragraph', models.CharField(default='1em', max_length=10)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicableroles', models.CharField(blank=True, max_length=200, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('featured_image', models.ImageField(upload_to='blog_images/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('reading_time', models.CharField(blank=True, max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('audience_segment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('rm_id', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('rm', 'Relationship Manager')], max_length=50)),
                ('rate_type', models.CharField(choices=[('percent', 'Percentage'), ('lumpsum', 'Lumpsum Amount'), ('fixed', 'Fixed Amount')], max_length=50)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('release_option', models.CharField(choices=[('15th', 'Release on 15th of next month'), ('custom', 'Custom Date'), ('hold', 'Hold Payment')], max_length=50)),
                ('custom_release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('seo_meta', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='dynamic_pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(upload_to='hero_images/')),
                ('title_font_size', models.CharField(default='48px', max_length=10)),
                ('subtitle_font_size', models.CharField(default='18px', max_length=10)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('overlay_color', models.CharField(default='#080808b3', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=60)),
                ('meta_title', models.CharField(max_length=60)),
                ('canonical_url', models.URLField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=160)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('template', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
