# Generated by Django 6.0.1 on 2026-03-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_agency_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_license_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
