# Generated by Django 5.2.4 on 2025-11-26 07:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class (e.g. bi bi-key)', max_length=50)),
                ('short_description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
        migrations.DeleteModel(
            name='Addon',
        ),
    ]
