# Generated by Django 6.0.1 on 2026-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_user_details_user_agency_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Type_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, max_length=200, null=True)),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('service_upload_date', models.DateField(blank=True, null=True)),
                ('service_upload_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
