# Generated by Django 5.2.4 on 2026-01-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_admin_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='reading_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
