# Generated by Django 6.0.1 on 2026-03-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_service_type_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='selected_regions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_gstin_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_operational_scope',
            field=models.CharField(default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_pan_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_service_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
