# Generated by Django 5.2.4 on 2026-03-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_alter_blog_category_alter_blog_reading_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ameneties_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenties_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('amenties_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amenties_date', models.DateField(blank=True, null=True)),
                ('amenties_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_email', models.CharField(blank=True, max_length=200, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('user_state', models.CharField(blank=True, max_length=200, null=True)),
                ('user_city', models.CharField(blank=True, max_length=200, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_password', models.CharField(blank=True, max_length=200, null=True)),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to='Profile/')),
                ('user_role', models.CharField(blank=True, max_length=200, null=True)),
                ('user_register_date', models.DateField(blank=True, null=True)),
                ('user_register_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
