# Generated by Django 6.0.1 on 2026-03-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_user_details_selected_regions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_operational_scope',
            field=models.CharField(blank=True, default='all', max_length=10, null=True),
        ),
    ]
