# Generated by Django 5.2.4 on 2025-11-26 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('landlord', 'Landlord'), ('broker', 'Broker / Agent')], max_length=20)),
                ('property_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area_locality', models.CharField(max_length=150)),
                ('property_address', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('builtup_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_App.leadcapture')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
