# Generated by Django 5.2.4 on 2026-03-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0002_resaleproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialListingProperty',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('property_title', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=100)),
                ('bhk', models.CharField(max_length=50)),
                ('renting_option', models.CharField(max_length=100)),
                ('built_up_area', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('floor_number', models.CharField(max_length=50)),
                ('total_floors', models.IntegerField()),
                ('facing', models.CharField(max_length=50)),
                ('furnishing', models.CharField(max_length=100)),
                ('available_for', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('ownership_type', models.CharField(max_length=100)),
                ('construction_status', models.CharField(max_length=100)),
                ('property_age', models.CharField(max_length=100)),
                ('carpet_area', models.IntegerField(blank=True, null=True)),
                ('plot_area', models.IntegerField(blank=True, null=True)),
                ('building_name', models.CharField(max_length=255)),
                ('possession_status', models.CharField(max_length=100)),
                ('available_from', models.DateField()),
                ('lease_duration', models.CharField(max_length=100)),
                ('brokerage', models.CharField(max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_type', models.CharField(max_length=100)),
                ('maintenance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('road_connectivity', models.CharField(max_length=100)),
                ('amenities', models.TextField()),
                ('description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('property_images', models.ImageField(blank=True, null=True, upload_to='residential_properties/')),
                ('owner_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('alternate_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
