# Generated by Django 5.2.4 on 2026-03-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0003_residentiallistingproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialListingProperty',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area_locality', models.CharField(max_length=150)),
                ('property_address', models.TextField()),
                ('building_project_society', models.CharField(max_length=200)),
                ('possession_status', models.CharField(max_length=100)),
                ('available_from', models.DateField()),
                ('property_age', models.CharField(max_length=100)),
                ('zone_type', models.CharField(max_length=100)),
                ('location_hub', models.CharField(max_length=100)),
                ('property_condition', models.CharField(max_length=100)),
                ('ownership_type', models.CharField(max_length=100)),
                ('construction_status', models.CharField(max_length=100)),
                ('built_up_area', models.CharField(max_length=50)),
                ('carpet_area', models.CharField(max_length=50)),
                ('expected_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maintenance_charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('negotiable', models.BooleanField(default=False)),
                ('dg_ups_included', models.BooleanField(default=False)),
                ('electricity_charges_included', models.BooleanField(default=False)),
                ('water_charges_included', models.BooleanField(default=False)),
                ('lock_in_period', models.CharField(max_length=50)),
                ('rent_increase_percentage', models.CharField(max_length=20)),
                ('total_floors', models.IntegerField()),
                ('your_floor', models.IntegerField()),
                ('number_of_staircase', models.IntegerField()),
                ('passenger_lifts', models.IntegerField()),
                ('service_lifts', models.IntegerField()),
                ('private_parking', models.IntegerField()),
                ('min_seats', models.IntegerField()),
                ('max_seats', models.IntegerField()),
                ('cabins', models.IntegerField()),
                ('meeting_rooms', models.IntegerField()),
                ('private_washroom', models.IntegerField()),
                ('public_washroom', models.IntegerField()),
                ('flooring_type', models.CharField(max_length=100)),
                ('property_images', models.ImageField(blank=True, null=True, upload_to='commercial_properties/')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='commercial_floorplans/')),
                ('video', models.FileField(blank=True, null=True, upload_to='commercial_videos/')),
                ('metro_stations_nearby', models.CharField(max_length=200)),
                ('bus_stops_nearby', models.CharField(max_length=200)),
                ('restaurants_cafes', models.CharField(max_length=200)),
                ('banks_atms', models.CharField(max_length=200)),
                ('amenities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
