# Generated by Django 5.2.4 on 2026-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0004_commerciallistingproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGColivingProperty',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('building_project', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=150)),
                ('pg_name', models.CharField(max_length=200)),
                ('property_address', models.TextField()),
                ('total_beds', models.IntegerField()),
                ('pg_for', models.CharField(max_length=50)),
                ('furnishing_type', models.CharField(max_length=100)),
                ('sharing_type', models.CharField(max_length=100)),
                ('best_suited_for', models.CharField(max_length=100)),
                ('meals_available', models.BooleanField(default=False)),
                ('meal_offerings', models.CharField(max_length=200)),
                ('meal_speciality', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=50)),
                ('lock_in_period', models.CharField(max_length=50)),
                ('minimum_stay', models.CharField(max_length=50)),
                ('available_from', models.DateField()),
                ('property_managed_by', models.CharField(max_length=100)),
                ('manager_stays', models.BooleanField(default=False)),
                ('common_area', models.CharField(max_length=200)),
                ('non_veg_allowed', models.BooleanField(default=False)),
                ('opposite_sex_allowed', models.BooleanField(default=False)),
                ('any_time_allowed', models.BooleanField(default=False)),
                ('visitors_allowed', models.BooleanField(default=False)),
                ('guardian_allowed', models.BooleanField(default=False)),
                ('drinking_allowed', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('room_type', models.CharField(max_length=100)),
                ('beds_in_room', models.IntegerField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_facilities', models.TextField()),
                ('property_images', models.ImageField(blank=True, null=True, upload_to='pg_properties/')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='pg_floorplans/')),
                ('video', models.FileField(blank=True, null=True, upload_to='pg_videos/')),
                ('nearby_colleges', models.CharField(max_length=200)),
                ('nearby_it_parks', models.CharField(max_length=200)),
                ('metro_bus_stops', models.CharField(max_length=200)),
                ('markets_malls', models.CharField(max_length=200)),
                ('amenities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
