# Generated by Django 5.2.4 on 2026-03-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0005_pgcolivingproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommercialListingProperty',
        ),
        migrations.DeleteModel(
            name='PGColivingProperty',
        ),
        migrations.DeleteModel(
            name='ResidentialListingProperty',
        ),
    ]
