# Generated by Django 5.2.4 on 2025-11-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200)),
                ('free_value', models.CharField(blank=True, max_length=100)),
                ('standard_value', models.CharField(blank=True, max_length=100)),
                ('premium_value', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeadPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=50)),
                ('wallet_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Landlord', 'Landlord'), ('Agent', 'Agent'), ('Tenant', 'Tenant')], max_length=20)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(help_text='Comma separated feature list')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WalletRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Credit/Debit', 'Credit/Debit'), ('NetBanking', 'NetBanking'), ('Cash', 'Cash')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Landlord', 'Landlord'), ('Agent', 'Agent'), ('Tenant', 'Tenant')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('amenities', models.CharField(blank=True, max_length=255)),
                ('agency_name', models.CharField(blank=True, max_length=150)),
                ('service_areas', models.CharField(blank=True, max_length=255)),
                ('preferred_locations', models.CharField(blank=True, max_length=255)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent_Dashboard.subscriptionplan')),
            ],
        ),
    ]
