# Generated by Django 6.0.1 on 2026-03-10 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_service', models.CharField(max_length=100)),
                ('service_mode', models.CharField(choices=[('single', 'Single'), ('multi', 'Multi')], default='single', max_length=10)),
                ('services', models.JSONField(blank=True, default=list)),
                ('special_tags', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('company_reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_year', models.PositiveIntegerField(default=0)),
                ('service_description', models.TextField(blank=True)),
                ('coverage_km', models.PositiveIntegerField(default=25)),
                ('pricing_model', models.CharField(choices=[('flat', 'Flat'), ('km_based', 'Per km'), ('hourly', 'Hourly'), ('custom', 'Custom')], default='flat', max_length=20)),
                ('price_flat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('vendor_status', models.CharField(choices=[('normal', 'Normal'), ('verified', 'Verified'), ('featured', 'Featured'), ('sponsored', 'Sponsored')], default='normal', max_length=20)),
                ('commission_rate', models.FloatField(blank=True, help_text='Vendor share % (60 = 60%)', null=True)),
                ('cumulative_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('accepted_leads', models.PositiveIntegerField(default=0)),
                ('is_inhouse', models.BooleanField(default=False)),
                ('is_rm_candidate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assigned_rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid to vendor in this transaction', max_digits=12)),
                ('paid_to_vendor', models.BooleanField(default=False)),
                ('paid_to_platform', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Vendors.commissionledger')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=64, unique=True)),
                ('customer_name', models.CharField(default='', max_length=150)),
                ('customer_mobile', models.CharField(default='', max_length=20)),
                ('service', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('pickup_address', models.TextField(blank=True)),
                ('drop_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('preferred_dt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_vendors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('shared', 'Shared'), ('assigned', 'Assigned'), ('no_response', 'No Response'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assigned_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to='Vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='enquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='Vendors.serviceenquiry'),
        ),
        migrations.CreateModel(
            name='LeadShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_shares', to='Vendors.serviceenquiry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_shares', to='Vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendors.vendor'),
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vendor_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Vendors.vendor')),
            ],
        ),
    ]
