# Generated by Django 5.1.5 on 2025-10-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180, unique=True)),
                ('pagetype', models.CharField(max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('primary_keyword', models.CharField(blank=True, max_length=150)),
                ('secondary_keywords', models.CharField(blank=True, max_length=255)),
                ('intro_html', models.TextField(blank=True)),
                ('schema_json', models.TextField(blank=True)),
                ('noindex', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='SeoMeta',
        ),
    ]
